'use strict';

module.exports = {
	SERVER: {
		'MOVIE_LIST': 'SERVER_MOVIE_LIST',
		'SEARCH_MOVIES': 'SERVER_SEARCH_MOVIES',
		'SEARCH_END' : 'SERVER_SEARCH_END',
		'GET_MOVIE' : 'SERVER_GET_MOVIE',
		'LOAD_MSG' : 'SERVER_LOAD_MSG'
	}
};